config/routes.rb
RailsApp::Application.routes.draw do
  resources :home_tasks, :path => '/hometask'

  get "test/index"

  resources :domobs
  resources :exchanges
  resources :members do
    member do
      post 'exchange10'
      post 'exchange20'
      post 'exchange30'
    end
  end

  resources :youmi

  controller :points do
    get '/points/youmicallback'
    get '/points/domobcallback'
  end

  controller :api do
    post '/api/registeruser'
    post '/api/getuserinfo'
    post '/api/exchange'
    post '/api/gettasklist'
    post '/api/getexchangelist'
    post '/api/checkin'
    post '/api/gethometasklist'
    get '/api/registeruser'
    get '/api/getuserinfo'
    get '/api/exchange'
    get '/api/gettasklist'
    get '/api/getexchangelist'
    get '/api/checkin'
    get '/api/gethometasklist'
  end

  devise_for :admins, only: [:session], :path => '/admin', :path_names => {:sign_in => 'login', :sign_out => 'logout'}

  resources :tasks, :path => '/userTaskList' do
    collection do 
      get 'reviewed'
      get '/youmi' => 'tasks#youmitask'
      get '/domob' => 'tasks#domobtask'
    end
  end

  root :to => 'tasks#index'

end

app/models/home_task.rb
class HomeTask < ActiveRecord::Base
  attr_accessible :description, :title, :task_type, :published
end

app/controllers/home_tasks_controller.rb
class HomeTasksController < ApplicationController
  # GET /home_tasks
  # GET /home_tasks.json
  def index
    @home_tasks = HomeTask.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @home_tasks }
    end
  end

  # GET /home_tasks/1
  # GET /home_tasks/1.json
  def show
    @home_task = HomeTask.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @home_task }
    end
  end

  # GET /home_tasks/new
  # GET /home_tasks/new.json
  def new
    @home_task = HomeTask.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @home_task }
    end
  end

  # GET /home_tasks/1/edit
  def edit
    @home_task = HomeTask.find(params[:id])
  end

  # POST /home_tasks
  # POST /home_tasks.json
  def create
    @home_task = HomeTask.new(params[:home_task])

    respond_to do |format|
      if @home_task.save
        format.html { redirect_to @home_task, notice: 'Home task was successfully created.' }
        format.json { render json: @home_task, status: :created, location: @home_task }
      else
        format.html { render action: "new" }
        format.json { render json: @home_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /home_tasks/1
  # PUT /home_tasks/1.json
  def update
    @home_task = HomeTask.find(params[:id])

    respond_to do |format|
      if @home_task.update_attributes(params[:home_task])
        format.html { redirect_to @home_task, notice: 'Home task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @home_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /home_tasks/1
  # DELETE /home_tasks/1.json
  def destroy
    @home_task = HomeTask.find(params[:id])
    @home_task.destroy

    respond_to do |format|
      format.html { redirect_to home_tasks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/home_tasks_helper.rb
module HomeTasksHelper
end

app/views/home_tasks/_form.html.haml
.col-md-4
  = simple_form_for(@home_task) do |f|
    = f.error_notification

    .form-inputs
      = f.input :title, label: "名称", :input_html => { :class => 'form-control' }, wrapper_html: { class: 'form-group'}
      = f.input :description, label: "内容", :input_html => { :class => 'form-control' }, wrapper_html: { class: 'form-group'}
      = f.input :task_type, label: "类型", :input_html => { :class => 'form-control' }, wrapper_html: { class: 'form-group'}
      = f.input :published, as: :boolean, label: "发布", :input_html => { :class => 'form-control' }, wrapper_html: { class: 'form-group'}

    .form-actions
      = f.button :submit, "创建", class: 'btn btn-primary'
      = link_to "取消", home_tasks_path, class: 'btn btn-info'

app/views/home_tasks/edit.html.haml
%h1 Editing home_task

= render 'form'

app/views/home_tasks/index.html.haml
.row
  .col-md-8
    %h1 页面任务列表
    %table.table.table-hover#home-task-list
      %tr
        %th 名称
        %th 描述
        %th 类型
        %th 发布
        %th 操作

      - @home_tasks.each do |home_task|
        %tr
          %td= home_task.title
          %td= home_task.description
          %td= home_task.task_type
          %td
            = home_task.published ? 'Y':'N'
          %td
            = link_to '编辑', edit_home_task_path(home_task)
            = link_to '删除', home_task, :method => :delete, :data => { :confirm => 'Are you sure?' }
    %p
      = link_to '新建', new_home_task_path, class: 'btn btn-primary'

app/views/home_tasks/new.html.haml
%h1 新建界面列表

= render 'form'

app/views/home_tasks/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @home_task.title
%p
  %b Description:
  = @home_task.description
%p
  %b Type:
  = @home_task.task_type

= link_to 'Edit', edit_home_task_path(@home_task)
\|
= link_to 'Back', home_tasks_path