config/routes.rb
RailsApp::Application.routes.draw do
  resources :home_tasks, :path => '/hometask'

  get "test/index"

  resources :domobs
  resources :exchanges
  resources :members do
    member do
      post 'exchange10'
      post 'exchange20'
      post 'exchange30'
    end
  end

  resources :youmi

  controller :points do
    get '/points/youmicallback'
    get '/points/domobcallback'
  end

  controller :api do
    post '/api/registeruser'
    post '/api/getuserinfo'
    post '/api/exchange'
    post '/api/gettasklist'
    post '/api/getexchangelist'
    post '/api/checkin'
    post '/api/gethometasklist'
    get '/api/registeruser'
    get '/api/getuserinfo'
    get '/api/exchange'
    get '/api/gettasklist'
    get '/api/getexchangelist'
    get '/api/checkin'
    get '/api/gethometasklist'
  end

  devise_for :admins, only: [:session], :path => '/admin', :path_names => {:sign_in => 'login', :sign_out => 'logout'}

  resources :tasks, :path => '/userTaskList' do
    collection do 
      get 'reviewed'
      get '/youmi' => 'tasks#youmitask'
      get '/domob' => 'tasks#domobtask'
    end
  end

  root :to => 'tasks#index'

end

app/models/domob.rb
class Domob < ActiveRecord::Base
  attr_accessible :ad, :adid, :channel, :device, :orderid, :point, :price, :pubid, :sign, :ts, :user

  before_save do |domob|
    WORKER_LOG.info "Will create new point from Youmi #{domob.orderid}, #{domob.pubid}, #{domob.adid}!"
  end
  
  after_save :create_task

  protected
    def create_task
      WORKER_LOG.info "New point for Domob ID: #{self.id}!"

      task = Task.new
      task.order_id = self.id
      task.order_type = 2
      task.member_name = self.user
      task.points = self.point

      if task.save
        WORKER_LOG.info "Create new task ID: #{task.id}, Order ID: #{task.order_id}, Order Type: #{task.order_type}!"
      end
    end
end

app/controllers/domobs_controller.rb
class DomobsController < ApplicationController
  # GET /domobs
  # GET /domobs.json
  def index
    @domobs = Domob.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @domobs }
    end
  end

  # GET /domobs/1
  # GET /domobs/1.json
  def show
    @domob = Domob.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @domob }
    end
  end

  # GET /domobs/new
  # GET /domobs/new.json
  def new
    @domob = Domob.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @domob }
    end
  end

  # GET /domobs/1/edit
  def edit
    @domob = Domob.find(params[:id])
  end

  # POST /domobs
  # POST /domobs.json
  def create
    @domob = Domob.new(params[:domob])

    respond_to do |format|
      if @domob.save
        format.html { redirect_to @domob, notice: 'Domob was successfully created.' }
        format.json { render json: @domob, status: :created, location: @domob }
      else
        format.html { render action: "new" }
        format.json { render json: @domob.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /domobs/1
  # PUT /domobs/1.json
  def update
    @domob = Domob.find(params[:id])

    respond_to do |format|
      if @domob.update_attributes(params[:domob])
        format.html { redirect_to @domob, notice: 'Domob was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @domob.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /domobs/1
  # DELETE /domobs/1.json
  def destroy
    @domob = Domob.find(params[:id])
    @domob.destroy

    respond_to do |format|
      format.html { redirect_to domobs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/domobs_helper.rb
module DomobsHelper
end

app/views/domobs/_form.html.haml
= simple_form_for(@domob) do |f|
  = f.error_notification

  .form-inputs
    = f.input :orderid
    = f.input :pubid
    = f.input :ad
    = f.input :adid
    = f.input :user
    = f.input :device
    = f.input :channel
    = f.input :price
    = f.input :point
    = f.input :ts
    = f.input :sign

  .form-actions
    = f.button :submit

app/views/domobs/edit.html.haml
%h1 Editing domob

= render 'form'

= link_to 'Show', @domob
\|
= link_to 'Back', domobs_path

app/views/domobs/index.html.haml
%h1 Listing domobs

%table
  %tr
    %th Orderid
    %th Pubid
    %th Ad
    %th Adid
    %th User
    %th Device
    %th Channel
    %th Price
    %th Point
    %th Ts
    %th Sign
    %th
    %th
    %th

  - @domobs.each do |domob|
    %tr
      %td= domob.orderid
      %td= domob.pubid
      %td= domob.ad
      %td= domob.adid
      %td= domob.user
      %td= domob.device
      %td= domob.channel
      %td= domob.price
      %td= domob.point
      %td= domob.ts
      %td= domob.sign
      %td= link_to 'Show', domob
      %td= link_to 'Edit', edit_domob_path(domob)
      %td= link_to 'Destroy', domob, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Domob', new_domob_path

app/views/domobs/new.html.haml
%h1 New domob

= render 'form'

= link_to 'Back', domobs_path

app/views/domobs/show.html.haml
%p#notice= notice

%p
  %b Orderid:
  = @domob.orderid
%p
  %b Pubid:
  = @domob.pubid
%p
  %b Ad:
  = @domob.ad
%p
  %b Adid:
  = @domob.adid
%p
  %b User:
  = @domob.user
%p
  %b Device:
  = @domob.device
%p
  %b Channel:
  = @domob.channel
%p
  %b Price:
  = @domob.price
%p
  %b Point:
  = @domob.point
%p
  %b Ts:
  = @domob.ts
%p
  %b Sign:
  = @domob.sign

= link_to 'Edit', edit_domob_path(@domob)
\|
= link_to 'Back', domobs_path