config/routes.rb
RailsApp::Application.routes.draw do
  resources :home_tasks, :path => '/hometask'

  get "test/index"

  resources :domobs
  resources :exchanges
  resources :members do
    member do
      post 'exchange10'
      post 'exchange20'
      post 'exchange30'
    end
  end

  resources :youmi

  controller :points do
    get '/points/youmicallback'
    get '/points/domobcallback'
  end

  controller :api do
    post '/api/registeruser'
    post '/api/getuserinfo'
    post '/api/exchange'
    post '/api/gettasklist'
    post '/api/getexchangelist'
    post '/api/checkin'
    post '/api/gethometasklist'
    get '/api/registeruser'
    get '/api/getuserinfo'
    get '/api/exchange'
    get '/api/gettasklist'
    get '/api/getexchangelist'
    get '/api/checkin'
    get '/api/gethometasklist'
  end

  devise_for :admins, only: [:session], :path => '/admin', :path_names => {:sign_in => 'login', :sign_out => 'logout'}

  resources :tasks, :path => '/userTaskList' do
    collection do 
      get 'reviewed'
      get '/youmi' => 'tasks#youmitask'
      get '/domob' => 'tasks#domobtask'
    end
  end

  root :to => 'tasks#index'

end

app/models/exchange.rb
class Exchange < ActiveRecord::Base
  attr_accessible :points, :type, :member_id
  belongs_to :member
end

app/controllers/exchanges_controller.rb
class ExchangesController < ApplicationController
  # GET /exchanges
  # GET /exchanges.json
  def index
    @exchanges = Exchange.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @exchanges }
    end
  end

  # GET /exchanges/1
  # GET /exchanges/1.json
  def show
    @exchange = Exchange.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @exchange }
    end
  end

  # GET /exchanges/new
  # GET /exchanges/new.json
  def new
    @exchange = Exchange.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @exchange }
    end
  end

  # GET /exchanges/1/edit
  def edit
    @exchange = Exchange.find(params[:id])
  end

  # POST /exchanges
  # POST /exchanges.json
  def create
    @exchange = Exchange.new(params[:exchange])

    respond_to do |format|
      if @exchange.save
        format.html { redirect_to @exchange, notice: 'Exchange was successfully created.' }
        format.json { render json: @exchange, status: :created, location: @exchange }
      else
        format.html { render action: "new" }
        format.json { render json: @exchange.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /exchanges/1
  # PUT /exchanges/1.json
  def update
    @exchange = Exchange.find(params[:id])

    respond_to do |format|
      if @exchange.update_attributes(params[:exchange])
        format.html { redirect_to @exchange, notice: 'Exchange was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @exchange.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exchanges/1
  # DELETE /exchanges/1.json
  def destroy
    @exchange = Exchange.find(params[:id])
    @exchange.destroy

    respond_to do |format|
      format.html { redirect_to exchanges_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/exchanges_helper.rb
module ExchangesHelper
end

app/views/exchanges/_form.html.haml
= simple_form_for(@exchange) do |f|
  = f.error_notification

  .form-inputs
    = f.input :points
    = f.input :user_id
    = f.input :type

  .form-actions
    = f.button :submit

app/views/exchanges/edit.html.haml
%h1 Editing exchange

= render 'form'

= link_to 'Show', @exchange
\|
= link_to 'Back', exchanges_path

app/views/exchanges/index.html.haml
.row
  .col-md-8
    %h1 交易记录
    %table.table.table-hover#exchange-list
      %thead
        %tr
          %th 兑换积分
          %th 用户ID
          %th 兑换日期
          %th 操作
      %tbody
        - @exchanges.each do |exchange|
          %tr
            %td= exchange.points
            %td= exchange.member_id
            %td= exchange.created_at.strftime("%Y-%m-%d %H:%M:%S")
            %td{:data => {:id => "#{exchange.id}"}}  
              - if exchange.reviewed_type == 0
                %button.btn.btn-info.btn-sm.btn-exchange-review 审阅
                %button.btn.btn-info.btn-sm.btn-exchange-reject 拒绝
              - if exchange.reviewed_type == 1
                %button.btn.btn-info.btn-sm.disabled 已批准
              - if exchange.reviewed_type == 2
                %button.btn.btn-info.btn-sm.disabled 已拒绝

app/views/exchanges/new.html.haml
%h1 New exchange

= render 'form'

= link_to 'Back', exchanges_path

app/views/exchanges/show.html.haml
%p#notice= notice

%p
  %b Points:
  = @exchange.points
%p
  %b User:
  = @exchange.user_id
%p
  %b Type:
  = @exchange.type

= link_to 'Edit', edit_exchange_path(@exchange)
\|
= link_to 'Back', exchanges_path