config/routes.rb
RailsApp::Application.routes.draw do
  resources :home_tasks, :path => '/hometask'

  get "test/index"

  resources :domobs
  resources :exchanges
  resources :members do
    member do
      post 'exchange10'
      post 'exchange20'
      post 'exchange30'
    end
  end

  resources :youmi

  controller :points do
    get '/points/youmicallback'
    get '/points/domobcallback'
  end

  controller :api do
    post '/api/registeruser'
    post '/api/getuserinfo'
    post '/api/exchange'
    post '/api/gettasklist'
    post '/api/getexchangelist'
    post '/api/checkin'
    post '/api/gethometasklist'
    get '/api/registeruser'
    get '/api/getuserinfo'
    get '/api/exchange'
    get '/api/gettasklist'
    get '/api/getexchangelist'
    get '/api/checkin'
    get '/api/gethometasklist'
  end

  devise_for :admins, only: [:session], :path => '/admin', :path_names => {:sign_in => 'login', :sign_out => 'logout'}

  resources :tasks, :path => '/userTaskList' do
    collection do 
      get 'reviewed'
      get '/youmi' => 'tasks#youmitask'
      get '/domob' => 'tasks#domobtask'
    end
  end

  root :to => 'tasks#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_many :tasks
end

app/models/domob.rb
class Domob < ActiveRecord::Base
  attr_accessible :ad, :adid, :channel, :device, :orderid, :point, :price, :pubid, :sign, :ts, :user

  before_save do |domob|
    WORKER_LOG.info "Will create new point from Youmi #{domob.orderid}, #{domob.pubid}, #{domob.adid}!"
  end
  
  after_save :create_task

  protected
    def create_task
      WORKER_LOG.info "New point for Domob ID: #{self.id}!"

      task = Task.new
      task.order_id = self.id
      task.order_type = 2
      task.member_name = self.user
      task.points = self.point

      if task.save
        WORKER_LOG.info "Create new task ID: #{task.id}, Order ID: #{task.order_id}, Order Type: #{task.order_type}!"
      end
    end
end

app/models/exchange.rb
class Exchange < ActiveRecord::Base
  attr_accessible :points, :type, :member_id
  belongs_to :member
end

app/models/home_task.rb
class HomeTask < ActiveRecord::Base
  attr_accessible :description, :title, :task_type, :published
end

app/models/member.rb
class Member < ActiveRecord::Base
  attr_accessible :name, :alipay, :available_points, :last_order_id, :last_order_type, :phone, :total_points
  has_many :exchange_id

#  after_save :gen_name

  private
    def gen_name
      tname = 10000 + self.id
      self.name = tname.to_s
    end
end

app/models/task.rb
class Task < ActiveRecord::Base
  # order_type: [0, 'checkin'], [1, 'duomi'], [2, 'duomeng']
  attr_accessible :admin_id, :description, :name, :reviewed, :member_id, :member_name, :order_id, :order_type, :points, :reviewed_type
  belongs_to :admin

  scope :has_reviewed, where(:reviewed => true)
  scope :pending_reviewed, where(:reviewed => false)

  after_save :set_member_points

  def get_app_name
    order = get_task_order
    if order
      order.ad
    else
      "None"
    end
  end

  protected
    def get_task_order
      if self.order_type
        order_type = self.order_type
        if order_type == 1
          order = Youmi.find(self.order_id)
        elsif order_type == 2
          order = Domob.find(self.order_id)
        end
      end
    end

    def set_member_points
      # member_name = self.member_name
      # member = Member.find_by_name(member_name)
      member_id = self.member_name
      member = Member.find(member_id)
      if member
        WORKER_LOG.info "Existed member Name: #{member_name}!"
        old_total_points = member.total_points
        new_total_points = member.total_points + self.points
        old_available_points = member.available_points
        new_available_points = member.available_points + self.points
        new_last_order_id = self.order_id
        new_last_order_type = self.order_type

        if member.update_attributes(:total_points => new_total_points, :available_points => new_available_points, :last_order_id => new_last_order_id, :last_order_type => new_last_order_type )
          WORKER_LOG.info "Update member total_points succeed! ID: #{member.id}, Name: #{member_name}, Old total_points: #{old_total_points}, New total_points: #{new_total_points}, Old available_points: #{old_available_points}, New available_points: #{new_available_points}!"
        end
      # else
      #   member = Member.new
      #   member.name = member_name
      #   member.total_points = self.points
      #   member.credit = self.points
      #   member.last_order_id = self.order_id
      #   member.last_order_type = self.order_type

      #   if member.save
      #     WORKER_LOG.info "Create member succeed! ID: #{member.id}, Name: #{member_name}!"
      #   else
      #     WORKER_LOG.info "Create member failed! Name: #{member_name}!"
      #   end
      end
    end
end

app/models/youmi.rb
class Youmi < ActiveRecord::Base
  attr_accessible :ad, :adid, :app, :chn, :device, :order, :points, :price, :sig, :sign, :source, :time, :user

  before_save do |youmi|
    WORKER_LOG.info "Will create new point from Youmi #{youmi.order}, #{youmi.app}, #{youmi.adid}!"
  end
  
  after_save :create_task

  protected
    def create_task
      WORKER_LOG.info "New point for Youmi ID: #{self.id}!"

      task = Task.new
      task.order_id = self.id
      task.order_type = 1
      task.member_name = self.user
      task.member_id = self.user
      task.points = self.points

      if task.save
        WORKER_LOG.info "Create new task ID: #{task.id}, Order ID: #{task.order_id}, Order Type: #{task.order_type}!"
      end
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/domobs_helper.rb
module DomobsHelper
end

app/helpers/exchanges_helper.rb
module ExchangesHelper
end

app/helpers/front_helper.rb
module FrontHelper
end

app/helpers/home_tasks_helper.rb
module HomeTasksHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/points_helper.rb
module PointsHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/youmis_helper.rb
module YoumisHelper
end

app/views/admins/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/common/theme/_carousel.html.haml
#myCarousel.carousel.slide{style: "max-width:670px;max-height:447px;margin:auto"}
  %ol.carousel-indicators{style:"z-index:10;height:auto;overflow:hidden"}
  - @slides.each_with_index do |slide, index|
  - foo = "active" if ( index == 0 )
    %li{class: "#{foo}", data: {target: "#myCarousel", slide_to: "#{index}"}}
  .carousel-inner
    - @slides.each_with_index do |slide, index|
    - foo = "active" if index == 0
      .item{class: "#{foo}"}
        =image_tag slide.avatar.url(:large), {alt: "Slide-#{index}"}
        .container
          .carousel-caption{style: "top:10px"}
            #textcontainer{style:"float:right"}
              %h1
                %a{href:"/products",style:"color:#2E86BD"}
                  = slide.title
              %p{style:"color:#2E86BD"}= slide.summary

  %a.carousel-control.left{href: "#myCarousel", data: {slide: "prev"}}
    %span.glyphicon.glyphicon-chevron-left
  %a.carousel-control.right{href: "#myCarousel", data: {slide: "next"}}
    %span.glyphicon.glyphicon-chevron-right

:javascript
  $(document).ready(function() {
    $('#myCarousel').carousel({
      interval: 5000
    })
  })

app/views/common/theme/_footer.html.haml
.footer
  %p Footer section

app/views/common/theme/_head.html.haml
.row  
  = link_to '有米任务', youmi_tasks_path
  = link_to '退出登录', destroy_admin_session_path, method: :delete

app/views/common/theme/_top.html.haml
%p Top Section

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WRD Valves Site Administration</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="<%= root_url%>css/adminstyle.css" rel="stylesheet">
    <script src="<%= root_url%>js/accordian.pack.js" type="text/jscript"></script>

  </head>
  <body onload="new Accordian('basic-accordian',5,'header_highlight');">
    <%= render :partial => 'admin/common/head' %>   

     <%= yield %> 

    <%= render :partial => 'admin/common/footer' %>

  </body>
</html>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mobile Lake</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="<%= root_url %>css/bootstrap.min.css" rel="stylesheet">
    <%= stylesheet_link_tag "application" %>    
    <%= javascript_include_tag "application" %>  
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
      <div class="container">
        <%= render :partial => 'common/theme/top' %>
      </div>
      <div class="container" >
        <%= render :partial => 'common/theme/head' %>
      </div>
      <div class="container" >
        <%= yield %>
      </div>

      <div class="container">
        <footer>
          <%= render :partial => 'common/theme/footer' %>
        </footer>
      </div>


  <!-- Bootstrap core JavaScript
  ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  <!-- <script src="<%= root_url %>js/jquery-1.11.0.min.js"></script>  -->  
  <script src="<%= root_url %>js/bootstrap.min.js"></script>  
  </body>
</html>